# use the dockerhub images instead of building the images locally
# `docker-compose -f dockerhub-compose.yml up`

version: '3'
services:
  redis:
    image: "redis:alpine"
     # -save: disable persistence
    command: redis-server --save

  redis-web:
    image: remydewolf/rainbow:redis-web
    ports:
      - "5000:5000"

  java:
    depends_on:
      - redis
    image: remydewolf/rainbow:nsquare-java
    env_file: .env

  go:
    depends_on:
      - redis
    image: remydewolf/rainbow:nsquare-go
    env_file: .env

  rust:
    depends_on:
      - redis
    image: remydewolf/rainbow:nsquare-rust
    env_file: .env

  # base: python:3.8-alpine, python:3.8-buster, python:3.8-slim-buster
  python:
    depends_on:
      - redis
    image: remydewolf/rainbow:nsquare-python
    env_file: .env

  # base: ruby:alpine, ruby:slim-buster, ruby:buster
  ruby:
    depends_on:
      - redis
    image: remydewolf/rainbow:nsquare-ruby
    env_file: .env
