#!/bin/bash

# check if base image is specified
BASE="${DOCKER_TAG#*python-}"
if [ "$BASE" = "$DOCKER_TAG" ]; then
    # ex: nsquare-python
    docker build --build-arg COMPUTE=${DOCKER_TAG%-*} \
        -t $IMAGE_NAME .
else
    # ex: nsquare-python-3.8-alpine, BASE=python:3.8-alpine
    docker build --build-arg COMPUTE=${DOCKER_TAG%-*} \
        --build-arg BASE="python:$BASE" \
        -t $IMAGE_NAME .
fi
