#!/bin/bash

# Executes at build-time at dockerhub, and is triggered when a 
# commit is pushed to github.

# echo "Override build"

# ex: nsquare-go
# COMPUTE=${DOCKER_TAG%-*} #nsquare
# LANG=${DOCKER_TAG#*-} #go

# printf "COMPUTE=$COMPUTE"
docker build --build-arg COMPUTE=${DOCKER_TAG%-*} -t $IMAGE_NAME .