{{- $type := .Values.type | default "pod" -}}
{{ if eq $type "job" }}

{{- $root := . -}}

{{- range $image := .Values.images }}
  {{ $app := (split ":" $image)._1  | replace "." "-" }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $app }}
  labels:
    app: {{ $app }}
spec:
  completions: {{ $root.Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ $app }}
    spec:
      nodeSelector:
        runner: {{ $app }}
      restartPolicy: Never
      containers:
      - name: {{ $app }}
        image: {{ $image }}
        resources:
          requests:
            cpu: 5m
            memory: 10Mi
        env: 
        {{- range $envvar := $root.Values.env }}
        - name: {{ $envvar.name }}
          value: "{{ $envvar.value }}"
        {{- end }}
{{- end }}
{{- end }}
